version: '3'

services:
  ingester:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./env
    networks: 
      - postgres

networks:
  postgres:
    external:
      name: postgres_db_default
  
  # redash:
  #   external:
  #     name: redash_default

