version: "2"
x-redash-service: &redash-service
  image: redash/redash:8.0.0.b32245
  depends_on:
    - postgres
    - redis
  env_file: ./env
  restart: always
  networks:
      - custom_network
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5003:5000"
    environment:
      REDASH_WEB_WORKERS: 4
    networks:
      - custom-network
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
    networks:
      - custom-network
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
    networks:
      - custom-network
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
    networks:
      - custom-network
  redis:
    image: redis:5.0-alpine
    restart: always
    networks:
      - custom-network
  postgres:
    image: postgres:9.6-alpine
    env_file: ./env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - custom-network
  nginx:
    image: redash/nginx:latest
    ports:
      - "8000:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
    networks:
      - custom-network

networks:
  custom-network:
    external: true